22 docstrings
pnsaevik/effluent pull request #24
Opened 2023-06-12 11:55 UTC by pnsaevik

2023-06-12 12:11 UTC, pnsaevik commented
Hi, @castelao, would you have a look at this pull request? The compiled documentation can be found at https://effluent.readthedocs.io/en/22-docstrings/

2023-06-12 13:58 UTC, castelao commented
Sure. I'll check it later today.

2023-06-14 16:22 UTC, castelao requested changes
That works. Thanks for having considered adding docstrings. It helps even ourselves when we are back after 6 months of working on something else.

2023-06-15 05:59 UTC, pnsaevik commented on src/effluent/io.py
> -import pandas as pd
I actually didn't know that PEP8 discouraged function-level imports. My thought was to lazily load modules that are not always needed, and which have heavy load times ("heavy" = not in the blink of an eye). But pep8 usually has their reasons, so I'll go ahead and change it.

2023-06-15 09:15 UTC, pnsaevik commented on src/effluent/io.py
> -def write_nc_to_xr(nc_dset: nc.Dataset, xr_dset: xr.Dataset):
They were removed since sphinx was complaining. But I found the root of the problem (and the solution), and have added even more type hints now.

2023-06-15 09:47 UTC, merged